"""
mesh_service.py

This service is responsible for post-processing
the SMPL generated mesh before sending it to
Three.js or garment generation.

Pipeline

SMPL OBJ
    ↓
Load Mesh
    ↓
Smooth Mesh
    ↓
Repair Mesh
    ↓
Remove Noise
    ↓
Compute Normals
    ↓
Save Processed OBJ
"""

import os
import open3d as o3d

from backend.body_prediction.smpl.texture_loader import TextureLoader
from backend.body_prediction.smpl.material_generator import MaterialGenerator



class MeshService:
    """
    Handles mesh optimization and cleaning.
    """

    def __init__(self):
        TextureLoader()
        MaterialGenerator()

        base_dir = os.path.dirname(os.path.dirname(__file__))

        self.input_mesh = os.path.join(
            base_dir,
            "body_prediction",
            "smpl",
            "output",
            "human_body.obj"
        )

        self.output_mesh = os.path.join(
            base_dir,
            "static",
            "generated",
            "processed_body.obj"
        )

    ####################################################
    # Load Mesh
    ####################################################

    def load_mesh(self):
        """
        Load OBJ generated by SMPL.
        """

        mesh = o3d.io.read_triangle_mesh(self.input_mesh)

        print("Mesh Loaded")

        return mesh

    ####################################################
    # Smooth Mesh
    ####################################################

    def smooth_mesh(self, mesh, iterations=5):
        """
        Smooth rough edges.
        """

        print("Smoothing Mesh...")

        mesh = mesh.filter_smooth_simple(
            number_of_iterations=iterations
        )

        return mesh

    ####################################################
    # Repair Mesh
    ####################################################

    def repair_mesh(self, mesh):
        """
        Remove duplicated vertices,
        triangles and degenerated faces.
        """

        print("Repairing Mesh...")

        mesh.remove_duplicated_vertices()

        mesh.remove_duplicated_triangles()

        mesh.remove_degenerate_triangles()

        mesh.remove_non_manifold_edges()

        return mesh

    ####################################################
    # Remove Noise
    ####################################################

    def remove_noise(self, mesh):
        """
        Remove tiny isolated artifacts.
        """

        print("Removing Noise...")

        mesh.remove_unreferenced_vertices()

        return mesh

    ####################################################
    # Compute Normals
    ####################################################

    def compute_normals(self, mesh):
        """
        Compute normals for lighting.
        """

        print("Computing Normals...")

        mesh.compute_vertex_normals()

        return mesh

    ####################################################
    # Save Mesh
    ####################################################

    def save_mesh(self, mesh):
        """
        Save processed mesh.
        """

        o3d.io.write_triangle_mesh(
            self.output_mesh,
            mesh,
            write_ascii=True
        )

        print("Processed mesh saved")

        print(self.output_mesh)

    ####################################################
    # Complete Pipeline
    ####################################################

    def process_mesh(self):
        """
        Execute full mesh pipeline.
        """

        mesh = self.load_mesh()

        mesh = self.smooth_mesh(mesh)

        mesh = self.repair_mesh(mesh)

        mesh = self.remove_noise(mesh)

        mesh = self.compute_normals(mesh)

        self.save_mesh(mesh)

        return self.output_mesh


if __name__ == "__main__":

    service = MeshService()

    service.process_mesh()